// Generated by CoffeeScript 1.9.2
(function() {
  var Carousel, slideShow;

  $(document).ready(function() {
    if ($('.carousel__list').length) {
      Carousel.init();
    }
    if ($('.carousel').length) {
      return slideShow.init();
    }
  });

  Carousel = (function() {
    var _moveSlide;
    _moveSlide = function($this, direction, callback) {
      var activeSlide, activeSlideSibling, container, edgesElements, list, reqPosition, underEdgesElements;
      container = $this.closest('.carousel');
      list = container.find('.carousel__list');
      activeSlide = list.find('.carousel__item_active');
      activeSlideSibling = direction === 'next' ? activeSlide.next() : activeSlide.prev();
      reqPosition = activeSlideSibling.length ? activeSlideSibling.position().left : '';
      edgesElements = direction === 'next' ? activeSlide.nextAll().eq(2) : activeSlide.prev();
      underEdgesElements = direction === 'next' ? edgesElements.next() : edgesElements.prev();
      if (edgesElements.length) {
        return list.animate({
          'left': -reqPosition
        }, 300, function() {
          activeSlide.removeClass('carousel__item_active');
          activeSlideSibling.addClass('carousel__item_active');
          if (!underEdgesElements.length) {
            return callback.call($this);
          }
        });
      }
    };
    return {
      init: function() {
        return $('.carousel__btn').on('click', function(e) {
          var $this, direction;
          e.preventDefault();
          $this = $(this);
          direction = $this.hasClass('carousel__btn_next') ? 'next' : 'prev';
          _moveSlide($(this), direction, function() {
            var oppositeDirection;
            oppositeDirection = direction === 'next' ? 'prev' : 'next';
            $('.carousel__btn_' + direction).hide();
            return $('.carousel__btn_' + oppositeDirection).show();
          });
          return $this.siblings().show();
        });
      }
    };
  })();

  slideShow = (function() {
    var _changePic;
    _changePic = function($this) {
      var container, display, path;
      path = $this.data('fullimg');
      container = $this.closest('.carousel');
      display = container.find('.carousel__full-img');
      return display.fadeOut(300, function() {
        $this = $(this);
        $this.attr('src', path);
        return $this.on('load', function() {
          return $this.fadeIn(300);
        });
      });
    };
    return {
      init: function() {
        return $('.carousel__img').on('click', function(e) {
          e.preventDefault();
          return _changePic($(this));
        });
      }
    };
  })();

}).call(this);

//# sourceMappingURL=carousel.js.map
